### ISSUE TITLE
Completion handler

### ISSUE THREAD

**Issue by pronebird** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#27]
Why both completion and failure blocks take NSError parameters?

```objc
[assetsLibrary saveImageData:imageData toAlbum:@"Album" metadata:metadata 
completion:^(NSURL *assetURL, NSError *error) {
    // ...
} failure:^(NSError *error) {
    // ...
}];
```

**Comment by Kjuly** [comment]
Hi @pronebird , they're defined by iOS SDK, and the errors are different, as the DOC said:

> // This block is executed if the user does not grant access to the caller to access the data managed by the framework or if the data is currently unavailable.
> typedef void (^ALAssetsLibraryAccessFailureBlock)(NSError *error);

> // This block is executed when saving an image by -writeImageToSavedPhotosAlbum:completionBlock: finishes. The assetURL can later be used to reference the saved image.
> typedef void (^ALAssetsLibraryWriteImageCompletionBlock)(NSURL *assetURL, NSError *error);

Hope it helps :)

**Comment by pronebird** [comment]
I got it, it just weird that both handlers accept error, I'd expect one failure and one success block.

**Comment by Kjuly** [comment]
@pronebird u can wrap it with a success block instead of completion block. Just note that only invoke the success block when the error is nil in completion block.

```Obj-C
[assetsLibrary saveImageData:imageData toAlbum:@"Album" metadata:metadata 
completion:^(NSURL *assetURL, NSError *error) {
    if (! error) {
      success(assetURL);
    }
} failure:^(NSError *error) {
    // ...
}];
```
