### ISSUE TITLE
HI~Sir, I have a problem

### ISSUE THREAD

**Issue by Yexinglong** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#28]
_45-[EXUShareItModelVC createAlbumInPhoneAlbum:]_block_invoke_3: Failed to add the asset to the custom photo album: ALAssetsGroup failed to add asset: ALAsset - Type:Photo, URLs:assets-library://asset/asset.PNG?id=6C63CC8A-2060-42D6-8135-16AB635CB037&ext=PNG.

**Comment by Kjuly** [comment]
What's ur iOS version & lib version that used?

**Comment by Yexinglong** [comment]
Sorry so late to see your reply The new Git repository code, ios system 8.2

**Comment by Kjuly** [comment]
Hi @Yexinglong , seems the error is same to https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/issues/16. Can u check whether the desired photo album has been created before u adding photo there?

**Comment by Yexinglong** [comment]
Thank you for your answer I wish you a happy life
