### ISSUE TITLE
ios 8.3 recreate album

### ISSUE THREAD

**Issue by bosspopuli** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#29]
Anyone know if the iOS 8.3 has become the problem of storing photos in album a deleted before?

I have this nserror:
> Error Domain=LIB_ALAssetsLibrary_CustomPhotoAlbum Code=0 "ALAssetsGroup failed to add asset: ALAsset - Type:Photo, URLs:assets-library://asset/asset.JPG?id=7721AB18-4B9D-46E1-8DC5-2196E6E26F0F&ext=JPG." UserInfo=0x1754663c0 {NSLocalizedDescription=ALAssetsGroup failed to add asset: ALAsset - Type:Photo, URLs:assets-library://asset/asset.JPG?id=7721AB18-4B9D-46E1-8DC5-2196E6E26F0F&ext=JPG.}

EDIT: i modify the code with example and now i have this error:
> __29-[TicketViewController photo]_block_invoke417: Failed to add the asset to the custom photo album: ALAssetsGroup failed to add asset: ALAsset - Type:Photo, URLs:assets-library://asset/asset.JPG?id=DBF214F4-4D16-4A05-B6E0-11A636B13317&ext=JPG.

**Comment by Kjuly** [comment]
What's ur lib version used? Plz take a look at this issue (https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/issues/16) first, maybe will helps.

**Comment by bosspopuli** [comment]
Yes i import Photos.framework. and i use the last versión. The code allways pass for this else

 else {
          // code that always creates an album on iOS 7.x.x but fails
          // in certain situations such as if album has been deleted
          // previously on iOS 8.x.
          [self addAssetsGroupAlbumWithName:albumName
                                resultBlock:addPhotoToLibraryBlock
                               failureBlock:failure];
        }

**Comment by Kjuly** [comment]
Seems u cannot get the `PHPhotoLibrary` class, can confirm it?

```Obj-C
Class PHPhotoLibrary_class = NSClassFromString(@"PHPhotoLibrary");
if (PHPhotoLibrary_class) {
  ...
} else {
   // code that always creates an album on iOS 7.x.x but fails
   // in certain situations such as if album has been deleted
   // previously on iOS 8.x.
   [self addAssetsGroupAlbumWithName:albumName
                         resultBlock:addPhotoToLibraryBlock
                        failureBlock:failure];
}
```

**Comment by bosspopuli** [comment]
The demo project work fine. In my project in a last version worked fine but know don´t work.

![captura de pantalla 2015-04-21 a las 11 35 43](https://cloud.githubusercontent.com/assets/12036095/7249459/d0621c40-e81a-11e4-9ffa-a10f664feba7.png)

This in your class
```Obj-C
#import "ALAssetsLibrary+CustomPhotoAlbum.h"
#import <Photos/PHPhotoLibrary.h>
```
This in my class
```Obj-C
-(void)photo{
    
    UIImage *image = [ImageGenerator imageWithView:self.view];
    NSDateFormatter * dateFormatter = [NSDateFormatter new];
    [dateFormatter setDateFormat:@"YYYYMMDD"];
    _namePhoto = [dateFormatter stringFromDate:[NSDate date]];   
    [ImageGenerator saveImage:image name:_namePhoto];
    
    [self.library saveImage:image toAlbum:self.sessionData.merchant.merchantName completion:^(NSURL *assetURL, NSError *error) {
        if (error)
            DLog(@"ERROR SAVE ALBUM");
        [self performSelectorOnMainThread:@selector(endPhoto) withObject:nil waitUntilDone:YES];
    } failure:^(NSError *error) {
        DLog(@"FAILURE SAVE ALBUM");        
        [self performSelectorOnMainThread:@selector(endPhoto) withObject:nil waitUntilDone:YES];
    }];
}
```

**Comment by Kjuly** [comment]
# Step 1  
Generally, the `failure` block will be invoked if user denied ur app to access to the assets library. Plz make sure ur app is allowed to access the photos app in Settings.app.

---
# Step 2  
Seems u want to change the name for photo, then save it to album. Plz comment out the code snippet below to avoid other factors before do testing first.

```Obj-C
NSDateFormatter * dateFormatter = [NSDateFormatter new];
[dateFormatter setDateFormat:@"YYYYMMDD"];
_namePhoto = [dateFormatter stringFromDate:[NSDate date]];   
[ImageGenerator saveImage:image name:_namePhoto];
```

---
# Step 3  
Then check the value of `image` & `self.sessionData.merchant.merchantName`, make sure they're the one u want.

**Comment by bosspopuli** [comment]
In the Navigation project appear the Photos.framework but not in the target. I add the framework again and it works!!! Really thanks! When the xcode updated, it removed my framework...

Thanks again!

**Comment by Kjuly** [comment]
Haha, cool!
