### ISSUE TITLE
Can't create album with same name as a deleted one

### ISSUE THREAD

**Issue by zhw511006** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#32]
First, I call saveImage:toAlbum method and it work well, the "Ablum1' is created. 

Second, I delete "Album1", and run the code again. I get this error in this method
_assetForURLResultBlockWithGroup

What's your suggestions？ Thanks!

**Comment by Kjuly** [comment]
What's the iOS version & lib version u used?

**Comment by zhw511006** [comment]
I have tested this on iOS8.3 and latest lib version.

I simply use this code:

[_assetsLibrary saveImage:image
                      toAlbum:@"Album1"
                   completion:nil
                      failure:nil];

when I delete Album1 and run this code again, it will crash...

![screen shot 2015-06-02 at 9 20 46 am](https://cloud.githubusercontent.com/assets/2869093/7926705/b7800138-0908-11e5-9e50-29aec9a76327.png)

**Comment by zhw511006** [comment]
http://stackoverflow.com/questions/25807021/cannot-create-album-with-same-name-as-a-deleted-one-on-ios
I see this link and  fix this by adding photos.framwork. Thanks!

**Comment by Kjuly** [comment]
@zhw511006 cool :)
