### ISSUE TITLE
Add Photos.framework as one more Dependancy for iOS 8

### ISSUE THREAD

**Issue by iOSCuriosity** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#33]
Add Photos.framework as Dependancy, because when it is not imported, application is unable to create new album. While it works perfectly when a same named album is already available in Photos App.

There are only two dependancies : https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum#dependence

**Comment by Kjuly** [comment]
Hi @iOSCuriosity , thx for the suggestion, but @NSFish has already help to add the weak reference.

**Comment by Kjuly** [comment]
@iOSCuriosity updated the README now :)

**Comment by iOSCuriosity** [comment]
@kjuly thanks, it'll help others..
