### ISSUE TITLE
When custom album was deleted by somebody through system PhotoApp, execute -saveImage:toAlbum:completion:failure:will throw error

### ISSUE THREAD

**Issue by 551854173** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#38]
Error Domain=LIB_ALAssetsLibrary_CustomPhotoAlbum Code=0 "ALAssetsGroup failed to add asset: ALAsset - Photo, URLs:assets-library://asset/jpg?id=DB9A4152-9517-43D3-A587-5D5A8A50DAE3&ext= jpg." UserInfo=0x17027a740 {NSLocalizedDescription=ALAssetsGroup failed to add asset: ALAsset - Photo, URLs:assets-library://asset/jpg?id=DB9A4152-9517-43D3-A587-5D5A8A50DAE3&ext=jpg.}

**Comment by 551854173** [comment]
but the photo can still save to camera roll, just can't creat the custom album and throw error

**Comment by 551854173** [comment]
Look forward to your reply. thx~

**Comment by Kjuly** [comment]
Latest lib version? Have u imported the Photos.framework?

Plz refer to https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/issues/29 & https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/issues/32.

**Comment by 551854173** [comment]
Thx 4 your reply! It works well after import the Photos.framework!

**Comment by Kjuly** [comment]
Cool :)
