### ISSUE TITLE
ios8.4 sometimes fail when addAssetURL to album

### ISSUE THREAD

**Issue by AshStill** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#39]
- (void)assetForURL:(NSURL *)assetURL resultBlock:(ALAssetsLibraryAssetForURLResultBlock)resultBlock failureBlock:(ALAssetsLibraryAccessFailureBlock)failureBlock;

this function sometime return nil, which will lead the saveimage to failureblock.

**Comment by AshStill** [comment]
I think in ios8 , PHPhotolibrary should be an option to use
https://developer.apple.com/library/ios/documentation/Photos/Reference/PHPhotoLibrary_Class/index.html#//apple_ref/doc/uid/TP40014404

**Comment by Kjuly** [comment]
@AshStill yup, u do need to import Photos framework for ur project since iOS 8.

**Comment by AshStill** [comment]
@Kjuly I have imported Photos framework in my project and sometimes still fail when save asset to savedAlbum especially when updated to iOS8.4.1.

**Comment by Kjuly** [comment]
Hey @AshStill, what's the fail error that u got? I'll debug to c anything wrong w/ the new version when got time, pretty busy these days. sorry for that.

**Comment by AshStill** [comment]
@Kjuly I find an solution for these. I will make pull request once I've done.

**Comment by AshStill** [comment]
@Kjuly I think i finished with PHPhotoLibrary but the problem is that I can't return an assetUrl, because PHAsset has its own identifier but not assetUrl :sob:

**Comment by Kjuly** [comment]
@AshStill, sorry, still don't have time to take a look at it yet, will check it around this weekend. :)

**Comment by Kjuly** [comment]
Hi @AshStill , i tried on iOS 8.4.1, w/o any issue, even tried to delete the album first. Several questions need ur help to answer:

1. While u're saving photo by the `-saveImage:toAlbum:completion:failure`:  
    1.1. Was `completion` block invoked before u trying to show the photo? (Make sure the photo was saved exactally before using it, or u can use the cached original photo while in saving process.)  
    1.2. Or the `failure` block is invoked? If it is, what's the detail error?  
2. What's the detail error u got in `-assetForURL:resultBlock:failureBlock:`'s `failureBlock`?

B.t.w., it'll be good if u offer some code snippets. :)

**Comment by AshStill** [comment]
@Kjuly  In my case, in the following function, the asset is nil, so it leads to the failure block
_assetForURLResultBlockWithGroup:assetURL:completion:failure:

**Comment by AshStill** [comment]
I use following code in ios8 above in my case.

    -(void)performSaveImage:(UIImage*)image toAlbum:(NSString*)name completionHandler:(void(^)(BOOL success, NSError *error))completionHandler
    {
    PHFetchOptions *options = [[PHFetchOptions alloc] init];
    options.predicate = [NSPredicate predicateWithFormat:@"title = %@" , name];
    __block PHAssetCollection *album = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAny options:options].firstObject;
    if (!album)
    {
        [[PHPhotoLibrary sharedPhotoLibrary] performChangesAndWait:^{
            [PHAssetCollectionChangeRequest creationRequestForAssetCollectionWithTitle:name];
        } error:nil];
        album = [PHAssetCollection fetchAssetCollectionsWithType:PHAssetCollectionTypeAlbum subtype:PHAssetCollectionSubtypeAny options:options].firstObject;
    }
    [[PHPhotoLibrary sharedPhotoLibrary] performChanges:^{
        // Request creating an asset from the image.
        PHAssetChangeRequest *createAssetRequest = [PHAssetChangeRequest creationRequestForAssetFromImage:image];
        // Request editing the album.
        PHAssetCollectionChangeRequest *albumChangeRequest = [PHAssetCollectionChangeRequest changeRequestForAssetCollection:album];
        
        // Get a placeholder for the new asset and add it to the album editing request.
        PHObjectPlaceholder *assetPlaceholder = [createAssetRequest placeholderForCreatedAsset];
        [albumChangeRequest addAssets:@[ assetPlaceholder ]];
        
    } completionHandler:^(BOOL success, NSError *error) {
        if (completionHandler) {
            completionHandler(success,error);
        }
    }];
    }

**Comment by Kjuly** [comment]
> In my case, in the following function, the asset is nil, so it leads to the failure block
_assetForURLResultBlockWithGroup:assetURL:completion:failure:

Which one, [L157][1] or [L181][2]? And what's the `assetURL` u were trying to save?

B.t.w., can u try the latest code's demo? Let's c whether it works in ur environ.

  [1]: https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/blob/dev/ALAssetsLibrary-CustomPhotoAlbum/ALAssetsLibrary%2BCustomPhotoAlbum.m#L157
  [2]: https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/blob/dev/ALAssetsLibrary-CustomPhotoAlbum/ALAssetsLibrary%2BCustomPhotoAlbum.m#L181

**Comment by Onion520** [comment]
YEP,I have the same question . when debug in L157 or L181  ,it works ok  . without breakpoint it will  filled in L181  [group addAsset:asset]   with asset is nil
Sorry for my poor English

**Comment by Kjuly** [comment]
@Onion520
> without breakpoint it will filled in L181 [group addAsset:asset] with asset is nil  

Seems asset cannot be found.
What's the value of `assetURL`  in L185 for ur case?

**Comment by Onion520** [comment]
assets-library://asset/asset.mov?id=C10AB3B5-EE07-4D12-A4DD-14E976FA854E&ext=mov

when  put  a breakpoint in L157 or L181   the  move  can be  save  ok .
And This is only on my cell phone。  other phone didn't have  the question

**Comment by Onion520** [comment]
it aways field in [L87](https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/blob/1629b2d3b3adb084d6dbf73a55f9613c6b24ca8d/ALAssetsLibrary-CustomPhotoAlbum/ALAssetsLibrary%2BCustomPhotoAlbum.m#L87)  with asset is nil
