### ISSUE TITLE
Option to check if image exists in the newly created folder in gallery?

### ISSUE THREAD

**Issue by subinrevi** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#40]
Hi,

      Is there any method by which we can check that an image already exists in our folder?

**Comment by Kjuly** [comment]
Hi @subinrevi , u can just use the default method

```Obj-C
- (void)assetForURL:(NSURL *)assetURL
        resultBlock:(ALAssetsLibraryAssetForURLResultBlock)resultBlock
       failureBlock:(ALAssetsLibraryAccessFailureBlock)failureBlock
```
if image exists, will invoke `resultBlock`, otherwise, `failureBlock` will be invoked w/ error.

---
btw., from iOS 9, it's recommended to
> Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead.

**Comment by subinrevi** [comment]
Hi,

   -(void)saveImage:(UIImage*)image toAlbum:(NSString*)albumName withCompletionBlock:(SaveImageCompletion)completionBlock
{
    //write the image data to the assets library (camera roll)
    [self writeImageToSavedPhotosAlbum:image.CGImage orientation:(ALAssetOrientation)image.imageOrientation 
                        completionBlock:^(NSURL* assetURL, NSError* error) {
                              
                          //error handling
                          if (error!=nil) {
                              completionBlock(error);
                              return;
                          }

                          //add the asset to the custom photo album
                          [self addAssetURL: assetURL 
                                    toAlbum:albumName 
                        withCompletionBlock:completionBlock];
                          
                      }];
}

Iam using the above method to save images to a new album in my phone. But the images are getting saved to the camera roll as well. Can I prevent that?

**Comment by subinrevi** [comment]
Hi,

   -(void)saveImage:(UIImage*)image toAlbum:(NSString*)albumName withCompletionBlock:(SaveImageCompletion)completionBlock
{
    //write the image data to the assets library (camera roll)
    [self writeImageToSavedPhotosAlbum:image.CGImage orientation:(ALAssetOrientation)image.imageOrientation 
                        completionBlock:^(NSURL* assetURL, NSError* error) {
                              
                          //error handling
                          if (error!=nil) {
                              completionBlock(error);
                              return;
                          }

                          //add the asset to the custom photo album
                          [self addAssetURL: assetURL 
                                    toAlbum:albumName 
                        withCompletionBlock:completionBlock];
                          
                      }];
}

Iam using the above method to save images to a new album in my phone. But the images are getting saved to the camera roll as well. Can I prevent that?

**Comment by Kjuly** [comment]
I notice u've closed the issue, so everything is okay now, right? :)
