### ISSUE TITLE
Method to remove image from Camera Roll.

### ISSUE THREAD

**Issue by Athul-Raj** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#42]
Hi,
I could save my Captured image in Custom Photo Album, However along with it the image gets stored in camera roll, any method to remove images saved in camera roll or else can we restrict it from storing to Camera Roll.

**Comment by Kjuly** [comment]
As far as i know, there's no way to keep the image existing in Album only while the original one was deleted in Camera Roll. The relationship between them like that: the image in Camera Roll is the original image, and the one in Album is like symbolic link to original one.

I'd glad to know if there's a way can achieve the goal that u asked. :)
