### ISSUE TITLE
iOS9 cannot create new album group

### ISSUE THREAD

**Issue by xhzengAIB** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#43]
@Kjuly 

Hello!  In iPhone6 run on iOS9，Cannot create new album group.

Jack

**Comment by Kjuly** [comment]
Have u imported Photos.framework to ur project? it's required from iOS 8.

**Comment by xhzengAIB** [comment]
hi!
My project is based on the iOS9, mobile phone is iPhone6, system version is 9.1

**Comment by Kjuly** [comment]
@xhzengAIB yes, i know, but have u imported Photos.framework to ur project? As mentioned in https://github.com/Kjuly/ALAssetsLibrary-CustomPhotoAlbum/pull/25.

**Comment by xhzengAIB** [comment]
ok!   i know, import Photos.framewrok lib

**Comment by xhzengAIB** [comment]
Thanks！

**Comment by Kjuly** [comment]
@xhzengAIB np :)
