### ISSUE TITLE
ALAssetsLibraryChangedNotification

### ISSUE THREAD

**Issue by rgksugan** [Kjuly/ALAssetsLibrary-CustomPhotoAlbum#7]
Is is possible to get a notification if the files in a particular album are changed.

**Comment by Kjuly** [comment]
Hi @rgksugan , u can add observer with notification name: `ALAssetsLibraryChangedNotification`, and the `userInfo` offers

- ALAssetLibraryUpdatedAssetsKey
- ALAssetLibraryInsertedAssetGroupsKey
- ALAssetLibraryUpdatedAssetGroupsKey
- ALAssetLibraryDeletedAssetGroupsKey

You can get the updated items & groups with `NSURL` items in `NSSet` instance.

DOC:
> This notification will be sent when the contents of the ALAssetsLibrary have changed from under the app that is using the data.
The API user should retain the library object to receive this notification.
The userInfo may include the keys listed below, which identify specific ALAssets or ALAssetGroups that have become invalid and should be discarded. The values are NSSets of NSURLs which match the ALAssetPropertyURL and ALAssetsGroupPropertyURL properties. 
If the userInfo is nil, all ALAssets and ALAssetGroups should be considered invalid and discarded.
Modified ALAssets will be identified by the ALAssetLibraryUpdatedAssetsKey, but inserted or deleted ALAssets are identified by invalidating the containing ALAssetGroups.
